env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  React: writable
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  react/react-in-jsx-scope: 'off'
  react/forbid-prop-types: 'off'
  react/jsx-props-no-spreading: 'off'
  # react/jsx-filename-extension:
  #   - 1
  #   - extensions:
  #       - '.js'
  #       - '.jsx'